name: Trunk Code Quality setup
description: Set up dependencies for Trunk Code Quality
runs:
  using: composite
  steps:
    - name: Setup Bun
      uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest

    - name: Install dependencies in typescript projects
      shell: bash
      run: |
        bun install --frozen-lockfile
